### ISSUE TITLE
cucumber-lua doesn't work with current ruby/cucumber

### ISSUE THREAD

**Issue by Bigfootmech** [cucumber/cucumber-lua#7]
Steps to reproduce:

# GIVEN
Install Ruby (for cucumber) 
    https://rubyinstaller.org/downloads/ (allow putting ruby in your PATH)
Install Ruby gems (distribution/source package for ruby, similar to Pip for python, and LuaRocks for Lua)
    https://rubygems.org/pages/download
    as it says, DL the file, unzip it (ie: C:\rubygems-2.7.1)
    in command line, run 
     > ruby setup.rb
    add the binary to PATH
     > ;C:\rubygems-2.7.1\bin
Install Cucumber
     > gem install cucumber

(optional) Install MinGW (or a favourite compiler), and add it to PATH
     > ;C:\MinGW\bin

Install Lua version 5.2 source code (yes. this is a bitch.)
    https://stackoverflow.com/questions/16641826/how-do-i-build-lua-for-windows-using-mingw-and-msys
    https://www.lua.org/ftp/ -> unzip to anywhere (it has a containing folder)
    cd in to the containing folder, or move the contents of the containing folder to, ie: C:\lua
    from command line, run
     > mingw32-make PLAT=mingw
    in that folder. Lua binaries should be somewhere inside src now.
    
    Create a LUA_HOME Environment variable, for where you installed it, for easy reference later
     > LUA_HOME = C:\lua\src
    Add the src folder to PATH (LUA_HOME must be visible, so you can't add this to system vars,
        if home is a user var)
     > ;%LUA_HOME%
    
Install LuaRocks (this is also not the most fun)
    Download Luarocks binary https://luarocks.github.io/luarocks/releases/ (latest win32.zip)
    Open command window -> navigate to unzipped folder, and run command:

     > install /MW
     
     or, if you have a microsoft c++ compiler installer with "cl" in the path, and don't want to use ming,
     
     > install

    Add the luarocks to PATH
     > ;C:\Program Files (x86)\LuaRocks
    Add where rocks (busted,cucumber) put their binaries to PATH as well
     > ;%LUA_HOME%/systree/bin
     Add lua rocks path to LUA_PATH environment variable
     > ;%LUA_HOME%/systree/share/lua/5.2/?.lua
    Add lua dlls folder to LUA_CPATH
     > ;%LUA_HOME%/systree/lib/lua/5.2/?.dll
     
Install Lua Cucumber with luarocks https://github.com/cucumber/cucumber-lua
 > luarocks build https://raw.github.com/cucumber/cucumber-lua/master/cucumber-lua-0.0-2.rockspec

Download Calculator example from https://github.com/cucumber/cucumber-lua/tree/master/examples/calculator

# WHEN
Run
 > cucumber-lua

In another console run
 > cucumber

# THEN
Result:

```
undefined method `[]' for nil:NilClass (NoMethodError)
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/ast/location.rb:16:in `from_file_colon_line'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/step_definition.rb:12:in `initialize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:28:in `new'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:28:in `create_step_match'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:19:in `block in handle_success'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:18:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:18:in `handle_success'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/data_packet.rb:30:in `handle_with'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:23:in `call_remote'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/request_handler.rb:10:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:14:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol.rb:8:in `step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `block in step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby24-x64/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:62:in `call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:66:in `matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:47:in `result'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/filter.rb:62:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/compiler.rb:24:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:32:in `parse'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:21:in `compile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:74:in `run!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
C:/Ruby24-x64/bin/cucumber:23:in `load'
C:/Ruby24-x64/bin/cucumber:23:in `<main>'
```

**Comment by Bigfootmech** [comment]
#Further Investigation

if
 > cucumber-lua
isn't running, always returns 
    Unable to contact the wire server at localhost:9666. Is it up? (Cucumber::Wire::Connection::ConnectionError)
    
----------------------------------------------------------------------------
If it IS running, and given incorrect step name

Feature: True

  Scenario: Simplest test ever # features/true.feature:3
    Then blep                  # features/true.feature:4

1 scenario (1 undefined)
1 step (1 undefined)
0m0.033s

You can implement step definitions for undefined steps with these snippets:

Then("blep") do
  pending # Write code here that turns the phrase above into concrete actions
end
Then("blep", function ()

end)

----------------------------------------------------------------------------
If Ruby one is implemented

C:\lua\src\lua.exe: ./features/step_definitions/steps.lua:6: syntax error near '#'
stack traceback:
        [C]: in function 'dofile'
        C:\lua\src\systree/share/lua/5.2/cucumber.lua:54: in function 'ReloadSteps'
        C:\lua\src\systree/share/lua/5.2/cucumber.lua:96: in function 'Listen'
        C:\lua\src\systree/share/lua/5.2/cucumber.lua:118: in function 'StartListening'
        ...e\lib\luarocks\rocks\cucumber-lua\0.0-2\bin\cucumber-lua:3: in main chunk
        [C]: in ?

----------------------------------------------------------------------------

If Lua one is implemented

```
undefined method `[]' for nil:NilClass (NoMethodError)
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/ast/location.rb:16:in `from_file_colon_line'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/step_definition.rb:12:in `initialize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:28:in `new'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:28:in `create_step_match'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:19:in `block in handle_success'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:18:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:18:in `handle_success'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/data_packet.rb:30:in `handle_with'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:23:in `call_remote'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/request_handler.rb:10:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:14:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol.rb:8:in `step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `block in step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in `step_matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby24-x64/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:62:in `call'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:66:in `matches'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:47:in `result'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/filter.rb:62:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/compiler.rb:24:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:32:in `parse'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:21:in `compile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:74:in `run!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
C:/Ruby24-x64/bin/cucumber:23:in `load'
C:/Ruby24-x64/bin/cucumber:23:in `<main>'
```

**Comment by Bigfootmech** [comment]
Looking in to 
 > C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.0.0/lib/cucumber/core/ast/location.rb:16:in `from_file_colon_line'

```
        def self.from_file_colon_line(file_colon_line)
          file, raw_line = file_colon_line.match(/(.*):(\d+)/)[1..2]
          from_source_location(file, raw_line.to_i)
        end
```

It expects the Source to be formatted as 

 > filename:line

This is impossible in lua, as it doesn't track line numbers, and we're currently only using one file

**Comment by Bigfootmech** [comment]
Proposed good solution: ???

Proposed quick solution:

In 

> https://github.com/cucumber/cucumber-lua/blob/master/src/cucumber.lua:79

replace

` source = pattern,`

with

`    source = "lua." .. pattern .. ":0",`

**Comment by nuninhoneto** [comment]
I couldn't fix here ;( Could you help me?

On calculator example root folder, when run on console

> cucumber-lua

And in another console, on calculator example root folder, when run

> cucumber

I got on server console (cucumber-lua one)

```
Waiting for cucumber on 0.0.0.0:9666 (Ctrl+C to quit)
D:\Lua5.3.5\bin\lua.exe: ./features/step_definitions/steps.lua:1: module 'calculator' not found:
        no field package.preload['calculator']
        no file 'd:\lua5.3.5\/share/lua/5.3/calculator.lua'
        no file 'd:\lua5.3.5\/share/lua/5.3/calculator/init.lua'
        no file '%LUA_PATH%'
        no file 'd:\lua5.3.5\/lib/lua/5.3/calculator.dll'
        no file '%LUA_CPATH%'
stack traceback:
        [C]: in function 'require'
        ./features/step_definitions/steps.lua:1: in main chunk
        [C]: in function 'dofile'
        d:\lua5.3.5\/share/lua/5.3/cucumber.lua:52: in function 'cucumber.ReloadSteps'
        d:\lua5.3.5\/share/lua/5.3/cucumber.lua:94: in function 'cucumber.Listen'
        d:\lua5.3.5\/share/lua/5.3/cucumber.lua:116: in function 'cucumber.StartListening'
        ...b\luarocks\rocks-5.3\cucumber-lua\0.0-2\bin\cucumber-lua:3: in main chunk
        [C]: in ?
```

And on cucumber console

```
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
Foi forþado o cancelamento de uma conexÒo existente pelo host remoto. @ io_fillbuf - fd:4  (Errno::ECONNRESET)
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:45:in 'gets'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:45:in 'block in fetch_data_from_socket'
D:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:93:in 'block in timeout'
D:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:33:in 'block in catch'
D:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:33:in 'catch'
D:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:33:in 'catch'
D:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:108:in 'timeout'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:45:in 'fetch_data_from_socket'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connection.rb:22:in 'call_remote'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/request_handler.rb:10:in 'execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol/requests.rb:14:in 'execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/protocol.rb:8:in 'step_matches'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in 'block in step_matches'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in 'map'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-wire-0.0.1/lib/cucumber/wire/connections.rb:33:in 'step_matches'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/step_match_search.rb:20:in 'call'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/step_match_search.rb:20:in 'call'
D:/Ruby24-x64/lib/ruby/2.4.0/delegate.rb:83:in 'method_missing'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/step_match_search.rb:62:in 'call'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:66:in 'matches'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:47:in 'result'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:37:in 'find_match'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:33:in 'attempt_to_activate'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:29:in 'map'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:29:in 'new_test_steps'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:23:in 'test_case'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:12:in 'test_case'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/case.rb:25:in 'describe_to'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/filters/activate_steps.rb:12:in 'test_case'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/case.rb:25:in 'describe_to'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in 'block in done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in 'each'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in 'done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/filter.rb:62:in 'done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in 'done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/compiler.rb:24:in 'done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core/gherkin/parser.rb:39:in 'done'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core.rb:32:in 'parse'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-core-3.2.0/lib/cucumber/core.rb:21:in 'compile'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:75:in 'run!'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in 'execute!'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.2/bin/cucumber:9:in '<top (required)>'
D:/Ruby24-x64/bin/cucumber:23:in 'load'
D:/Ruby24-x64/bin/cucumber:23:in '<main>'
```

**Comment by nuninhoneto** [comment]
Okay, could we assume it is a Windows problem?

I did the following test:

> Ubuntu 18.04 amd64
> Lua-5.3.3 (from apt)
> Luarocks 2.4.1 (from source)
> Ruby 2.5.1 (from apt)
> Cucumber-wire 0.0.1-2 (from apt)
> Cucumber-core 1.5.0-1 (from apt)
> Cucumber 2.4.0-3 (from apt)

and

> Windows 7 x64-86
> Lua-5.3.5 (from source)
> Luarocks 2.4.1 (from binaries)
> Ruby 2.5.1 (from binaries)
> Gems 2.7.7 (from binaries)
> Cucumber-wire 0.0.1 (from gems)
> Cucumber-core 1.5.0 (from gems)
> Cucumber 2.4.0 (from gems explicit version)

and it executed well on Ubuntu version. ;(

Are there a debug mode?

**Comment by nuninhoneto** [comment]
Well, i found the problem on Windows... I dunno what moment the luarocks created the bat file on my lua\bin folder, but at that moment there were some missed and wrong things on the file. I tried to find how fix the rockspec file, but no luck (luarocks bad documentation).

Original bat file created 
```
@echo off

set "LUAROCKS_SYSCONFDIR=C:\Program Files (x86)\luarocks"

set "LUA_PATH=d:\lua5.3.5\/share/lua/5.3/?.lua;d:\lua5.3.5\/share/lua/5.3/?/init.lua;%%LUA_PATH%%"

set "LUA_CPATH=d:\lua5.3.5\/lib/lua/5.3/?.dll;%%LUA_CPATH%%"

set "LUA_INIT=local k,l,_=pcall(require,'luarocks.loader') _=k and l.add_context('cucumber-lua','0.0-2')"

"D:\Lua5.3.5\bin\lua.exe" "d:\lua5.3.5\lib\luarocks\rocks-5.3\cucumber-lua\0.0-2\bin\cucumber-lua" %*

exit /b %ERRORLEVEL%
```

I manually fixed the separator directory (dependent from OS) and add `?;?.lua;` to LUA_PATH and LUA_CPATH.

Fixed bat file
```
@echo off

set "LUAROCKS_SYSCONFDIR=C:\Program Files (x86)\luarocks"

set "LUA_PATH=?;?.lua;d:\lua5.3.5\share\lua\5.3\?.lua;d:\lua5.3.5\share\lua\5.3\?\init.lua;%%LUA_PATH%%"

set "LUA_CPATH=?;?.lua;d:\lua5.3.5\lib\lua\5.3\?.dll;%%LUA_CPATH%%"

set "LUA_INIT=local k,l,_=pcall(require,'luarocks.loader') _=k and l.add_context('cucumber-lua','0.0-2')"

"D:\Lua5.3.5\bin\lua.exe" "d:\lua5.3.5\lib\luarocks\rocks-5.3\cucumber-lua\0.0-2\bin\cucumber-lua" %*

exit /b %ERRORLEVEL%
```
